version: '3.8'
services:
  database:
    build: 
      context: ./database
      dockerfile: ./build/Dockerfile
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 1s
      timeout: 5s
      retries: 30
  database-api:
    build: 
      context: ./database-api
      dockerfile: ./build/Dockerfile
    env_file:
       - .env
    ports:
      - '5555:5555'
    depends_on:
      database:
        condition: service_healthy

volumes:
  database:
    driver: local
