version: '3.8'
services:
  database:
    build: 
      context: ./database
      dockerfile: ./build/Dockerfile
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - database:/var/lib/postgresql/data
  database-api:
    build: 
      context: ./database-api
      dockerfile: ./build/Dockerfile
    env_file:
       - .env
    ports:
      - '5555:5555'

volumes:
  database:
    driver: local
